apply plugin: 'com.android.application'

android {
    namespace 'jp.co.cyberagent.android.gpuimage.sample'
    compileSdkVersion COMPILE_SDK_VERSION as int

    defaultConfig {
        minSdkVersion MIN_SDK_VERSION as int
        targetSdkVersion TARGET_SDK_VERSION as int

        versionCode = VERSION_CODE as int
        versionName = VERSION_NAME
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            debuggable false
            zipAlignEnabled true
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
repositories {
//     maven { url = "https://oss.sonatype.org/content/repositories/snapshots"}
}

dependencies {
    implementation project(':library')
    implementation 'androidx.appcompat:appcompat:1.8.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.4.10"
}
